### PR TITLE
Merge MSEA branch into master branch

### PR DESCRIPTION
**Pull request by megahirt**
This is a draft PR to help facilitate merging the MSEAG branch into master.  Some work needs to be done in order for this merge to succeed.  We should consider whether the MSEA branch should simply become the master branch and abandon orphaned commits on master.

### CODE REVIEW

**Comment by megahirt** [comment]
@terrygibbs I have created a PR for merging MSEA into master, however there are merge conflicts because this has not been done in many years.  My recommendation is to make the MSEA branch the de-facto master branch (force push master) and discard orphaned commits on master.  What is your thought?

**Comment by kgorham** [comment]
@megahirt, will you be putting this into review?

**Comment by kgorham** [comment]
With regards to LIft "There is also an issue with using PA, since it crashes when I try to connect with FieldWorks."  As fars I code tell, the problem still resided in Fieldworks. That was about two years ago though.

**Comment by megahirt** [comment]
Hi @kgorham I mostly created the PR to see if it could automatically be merged via fast-forward (it cannot) and so my proposal is to simply abandon master and make the MSEA branch the master branch.  I'm trying just to clean things up a bit.  Would you agree with my proposal?  Maybe you know why master has commits that MSEA doesn't?

**Comment by kgorham** [comment]
@megahirt The only significant changes I see to master are the the ones made by corey w. in 2007 in preparation for v 3.0.1 and then I pushed a readme.md file in 2015.  It looks like I branched from master BEFORE Coreys change.  But I picked up his changes later : Merged revs 2265-2343 from trunk (SA 3.0.1). Commit: a2cc79c3 (open) on 1/2/2008.
I did try to merge master locally into MSEA, and saw the two conflicts for SA_DEU.RC and sa.cpp, so that could be resolved without too much trouble so that you can do a normal merge if you want to...

**Comment by megahirt** [comment]
Dear Kent,

Thank you for this helpful analysis!  If you are willing to resolve the
merge conflicts and merge master in MSEA, then that is great.  Otherwise, I
will simply reset master to the MSEA branch and we'll drop those old
commits (or maybe have a branch called "old-master" pointing to them).  Can
you comment on what the other branches are for, and whether they should be
kept around or not?

MSEA@2232
tags/3.0@2231
trunk@2264
tags/3.0@2263
tags/3.0
xp
VS2005
audiosync
find_paren_problem2

Warm regards,

Christopher Hirt
Team Manager - Thailand
SIL Language Software Development
chris_hirt@sil.org

**Comment by kgorham** [comment]
@megahirt sorry I got distracted with other things last night. I will try to take care of this tonight and respond to your questions.  Yes, I will do the resolve and merge as well later tonight.

**Comment by kgorham** [comment]
@megahirt  okay... didn't happen last night either. and not tonight.  hopefully i will get to this this weekend.  i will build and test as well.  i forgot i need to get my build environment back into shape.

**Comment by megahirt** [comment]
Great thanks Kent!  It's really OK with me if we abandon the master branch
and just use the MSEA branch.  So please don't spend lots of time on that
particular task.

One thing that would be super helpful is if you could document in detail
the developer environment setup and build setup, because I don't have any
experience or know how to actually build SA.  This could be documented in
the repo as a DEVELOPER.md or README.md  Maybe it's already there
someplace.  I haven't looked recently.

Kind regards,

Chris

**Comment by kgorham** [comment]
Hi Chris,

I've deleted old branches that are no longer needed.  
I fixed the conflicts and I've merged MSEA into master.
I've updated the installer script so that it uses relative locations for acquiring files.
I've reformatted the CHANGELOG.MD file and I've created a DEVELOPER.MD file.
I did rebuild everything and try out the installer script.  It should be good to go.
SA presently compiles with Visual Studio 2015.

So what are the future plans for SA?  Is it getting moth-balled, or is there intent to continue using / supporting it?

I do have a redmine database with other open issues that have been found during it's development.  If you want a report, I can try to get it to you.

- Kent

**Comment by megahirt** [comment]
Hi @kgorham !  So I'm replying to your comment over a year later  - many apologies for that.  Timing was bad for me around March last year as I was travelling during that time.

There is still use for SA, especially in MSEAG, and we'd still like to continue using / supporting it where possible.

Thanks again for all the work you've put into SA!

**Pull request merged**
