### PR TITLE
chore: Update SA_DEU.rc

### LINKED ISSUE #35: question: Is SA_DEU.rc up to date with SA_ENU.rc?
I just realized SA_DEU.rc is for German locale. We should check if the updates in 3.1.1.1 SA_ENU.rc (English locale) need to be applied to SA_DEU.rc too.

### PR DESCRIPTION
**Pull request by darcywong00**
Fixes #35 by copying some of the layout updates in v.3.1.1.1 of SA_ENU.rc into SA_DEU.rc.

### CODE REVIEW

**Review by megahirt — APPROVED** [review]
LGTM - I trust these edits are more/less identical to the edits to the ENU.rc file.

As I scanned the entire SA_DEU.rc file I was expecting to see some German strings used to localize the UI.  I couldn't find a single German string - so I wonder if this string localization feature is even being used?  @terrygibbs ?

**Comment by darcywong00** [comment]
> As I scanned the entire SA_DEU.rc file I was expecting to see some German strings used to localize the UI. I couldn't find a single German string - so I wonder if this string localization feature is even being used? @terrygibbs ?

The non-English string I saw was `Öffnen` instead of `Open`.

**Comment by megahirt** [comment]
Fantastic - one string.  How does one switch to the German UI ?

**Comment by darcywong00** [comment]
> Fantastic - one string. How does one switch to the German UI ?

I assumed it would switch if the Windows locale was German. Unfortunately, my Windows license is limited to 1 language, so I couldn't verify this.

**Pull request merged**
